<?php
class Twig_Tests_ErrorTest extends PHPUnit_Framework_TestCase { public function testErrorWithObjectFilename() { $sp4eefd6 = new Twig_Error('foo'); $sp4eefd6->setTemplateFile(new SplFileInfo(__FILE__)); $this->assertContains('test' . DIRECTORY_SEPARATOR . 'Twig' . DIRECTORY_SEPARATOR . 'Tests' . DIRECTORY_SEPARATOR . 'ErrorTest.php', $sp4eefd6->getMessage()); } public function testErrorWithArrayFilename() { $sp4eefd6 = new Twig_Error('foo'); $sp4eefd6->setTemplateFile(array('foo' => 'bar')); $this->assertEquals('foo in {"foo":"bar"}', $sp4eefd6->getMessage()); } public function testTwigExceptionAddsFileAndLineWhenMissingWithInheritanceOnDisk() { $spdfb5a9 = new Twig_Loader_Filesystem(dirname(__FILE__) . '/Fixtures/errors'); $speae043 = new Twig_Environment($spdfb5a9, array('strict_variables' => true, 'debug' => true, 'cache' => false)); $spe32893 = $speae043->loadTemplate('index.html'); try { $spe32893->render(array()); $this->fail(); } catch (Twig_Error_Runtime $spbcee8e) { $this->assertEquals('Variable "foo" does not exist in "index.html" at line 3', $spbcee8e->getMessage()); $this->assertEquals(3, $spbcee8e->getTemplateLine()); $this->assertEquals('index.html', $spbcee8e->getTemplateFile()); } try { $spe32893->render(array('foo' => new Twig_Tests_ErrorTest_Foo())); $this->fail(); } catch (Twig_Error_Runtime $spbcee8e) { $this->assertEquals('An exception has been thrown during the rendering of a template ("Runtime error...") in "index.html" at line 3.', $spbcee8e->getMessage()); $this->assertEquals(3, $spbcee8e->getTemplateLine()); $this->assertEquals('index.html', $spbcee8e->getTemplateFile()); } } public function testTwigExceptionAddsFileAndLine($sp34ff74, $sp3eec35, $sp1a6fde) { $spdfb5a9 = new Twig_Loader_Array($sp34ff74); $speae043 = new Twig_Environment($spdfb5a9, array('strict_variables' => true, 'debug' => true, 'cache' => false)); $spe32893 = $speae043->loadTemplate('index'); try { $spe32893->render(array()); $this->fail(); } catch (Twig_Error_Runtime $spbcee8e) { $this->assertEquals(sprintf('Variable "foo" does not exist in "%s" at line %d', $sp3eec35, $sp1a6fde), $spbcee8e->getMessage()); $this->assertEquals($sp1a6fde, $spbcee8e->getTemplateLine()); $this->assertEquals($sp3eec35, $spbcee8e->getTemplateFile()); } try { $spe32893->render(array('foo' => new Twig_Tests_ErrorTest_Foo())); $this->fail(); } catch (Twig_Error_Runtime $spbcee8e) { $this->assertEquals(sprintf('An exception has been thrown during the rendering of a template ("Runtime error...") in "%s" at line %d.', $sp3eec35, $sp1a6fde), $spbcee8e->getMessage()); $this->assertEquals($sp1a6fde, $spbcee8e->getTemplateLine()); $this->assertEquals($sp3eec35, $spbcee8e->getTemplateFile()); } } public function getErroredTemplates() { return array(array(array('index' => '

{{ foo.bar }}


{{ \'foo\' }}'), 'index', 3), array(array('index' => '{% include \'partial\' %}', 'partial' => '{{ foo.bar }}'), 'partial', 1), array(array('index' => '{% extends \'base\' %}
                    {% block content %}
                        {{ parent() }}
                    {% endblock %}', 'base' => '{% block content %}{{ foo.bar }}{% endblock %}'), 'base', 1), array(array('index' => '{% extends \'base\' %}
                    {% block content %}
                        {{ foo.bar }}
                    {% endblock %}
                    {% block foo %}
                        {{ foo.bar }}
                    {% endblock %}', 'base' => '{% block content %}{% endblock %}'), 'index', 3)); } } class Twig_Tests_ErrorTest_Foo { public function bar() { throw new Exception('Runtime error...'); } }